AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  thankshell-api

  Sample SAM Template for thankshell-api
  
Parameters:
  EnvName:
    Type: String
  GroupsTableName:
    Type: String
  GroupMembersTableName:
    Type: String
  InfoTableName:
    Type: String
  TransactionsTableName:
    Type: String
  TokenTransactionsTableName:
    Type: String
  Environment:
    Type: String
    AllowedValues:
    - staging
    - production
    Default: staging

Globals:
  Api:
    OpenApiVersion: 3.0.1
  Function:
    Timeout: 10
    Handler: index.handler
    Runtime: nodejs12.x
    Environment:
      Variables:
        GROUPS_TABLE_NAME: !Ref GroupsTableName
        GROUP_MEMBERS_TABLE_NAME: !Ref GroupMembersTableName
        TOKEN_TRANSACTIONS_TABLE_NAME: !Ref TokenTransactionsTableName

Resources:

  ###############################################
  # Api

  ThankshellApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: false
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:ap-northeast-1:027569216980:userpool/ap-northeast-1_GyRiCriHq
      Variables:
        transaction_database: !Ref EnvName
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"

  ###############################################
  # Layers

  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: thankshell-libs
      Description: Common Application Resource Layer
      ContentUri: src/layers/common

  #######################################
  # Functions

  #
  # User
  #

  GetUserInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_user_info/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /user
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  CreateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/create_user/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /user
            Method: put
            RestApiId: !Ref ThankshellApi
      Policies:
      Layers:
      - !Ref CommonLayer

  UpdateUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/update_user/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: patch
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  #
  # Groups
  #

  GetGroupInfo:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_groups
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /groups/{group}
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  AddMemberToGroup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/add_group_member
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /groups/{group}/members/{member}
            Method: put
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  RemoveMemberFromGroup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/delete_group_member
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /groups/{group}/members/{member}
            Method: delete
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  EntryToGroup:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/entry
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /groups/{group}/members/{member}/user
            Method: put
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  #
  # Token publiched
  #

  GetTokenPublished:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_token_published/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/published
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      Layers:
      - !Ref CommonLayer

  PublishToken:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/publish_token/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/published
            Method: post
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref InfoTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TransactionsTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TokenTransactionsTableName
      Layers:
      - !Ref CommonLayer

  #
  # Token Holders
  #

  GetTokenHolders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_token_holders/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/holders
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      - DynamoDBReadPolicy:
          TableName: !Ref InfoTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TransactionsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TokenTransactionsTableName
      Layers:
      - !Ref CommonLayer

  GetTokenHoldings:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_token_holdings/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/holders/{user}
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      - DynamoDBReadPolicy:
          TableName: !Ref InfoTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TransactionsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TokenTransactionsTableName
      Layers:
      - !Ref CommonLayer

  #
  # Token Transaction
  #

  GetTransactions:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/get_transactions/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/transactions
            Method: get
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      - DynamoDBReadPolicy:
          TableName: !Ref InfoTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TransactionsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref TokenTransactionsTableName
      Layers:
      - !Ref CommonLayer

  CreateTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/create_transaction/
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /token/{token}/transactions
            Method: post
            RestApiId: !Ref ThankshellApi
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref GroupsTableName
      - DynamoDBReadPolicy:
          TableName: !Ref GroupMembersTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref InfoTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TransactionsTableName
      - DynamoDBCrudPolicy:
          TableName: !Ref TokenTransactionsTableName
      Layers:
      - !Ref CommonLayer
